//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA45_9B_LibraryManaegmentSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.IssueTrans = new HashSet<IssueTran>();
        }
    
        public string ISBNNumber { get; set; }
        public string BookTitle { get; set; }
        public string Publisher { get; set; }
        public string Author { get; set; }
        public string BookLanguage { get; set; }
        public string CallNumber { get; set; }
        public Nullable<short> stockNumber { get; set; }
        public Nullable<short> RantedNumber { get; set; }
        public string Genre { get; set; }
        public Nullable<short> BookID { get; set; }
        public string Category { get; set; }
        public string Edition { get; set; }
        public Nullable<System.DateTime> PublicationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IssueTran> IssueTrans { get; set; }
    }
}
