//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA45_9B_LibraryManaegmentSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueTran
    {
        public short TransactionID { get; set; }
        public string MemberID { get; set; }
        public string ISBNNumber { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<System.DateTime> DateIssue { get; set; }
        public Nullable<System.DateTime> DateDue { get; set; }
        public Nullable<System.DateTime> DateActualReturn { get; set; }
        public string RentalStatus { get; set; }
        public string Remarks { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Member Member { get; set; }
    }
}
